### ISSUE TITLE
Lazy Loading?

### ISSUE THREAD

**Issue by oyeanuj** [Significa/react-snuggle#11]
Hi @danilowoz! Thank you for open-sourcing this library! Quick question - what is the best way to incorporate lazy loading into the library so that children not in view are not loaded?

Is that something that you see being part of this library? Or is there another workaround you'd recommend?

**Comment by danilowoz** [comment]
Hey @oyeanuj, great question!
Currently, I'm working on a solution for it, when I have a new release with this feature I'll get in touch you

Thanks :)

**Comment by stuckinaboot** [comment]
Just wanted to follow-up on this, is there a solution for this?

**Comment by danilowoz** [comment]
Hey, sorry for the late follow-up.
I've dug in this issue, and unfortunately, Snuggle is not able to provide great support for lazy-loading, so that of how it works and how it gets DOM in order to measure of item sizes. 

Let me try to explain why:
- The first Snuggle will render all elements at the top of its parents, without the right positions, in order to set a couple of events and get the items size;
- Meanwhile, the Lazy-loading component will fire the event to show the image, once all items are in the viewport, right?;
- Then, after the first render, Snuggle will reposition all items in the right place. 

Because of it, lazy-loading loses its right behavior, since it will load all images at the same time. Otherwise, in case it's not a big deal for you, Snuggle already has an API that provides a way to reposition all items on image loading:

```jsx
const Component = () => {
  const snuggleRef = useRef()

  const onLoad = () => {
    if (snuggleRef.current) {
      snuggleRef.current.resize()
    }
  }

  return (
    <Snuggle ref={snuggleRef}>
      <img src="example.jpg" onLoad={onLoad} />
    </Snuggle>
  )
}
```

Hope it helps! Thanks
